armv8a : Fix Compilation errors in compiling armv8a machines
problem : copliation errors like
"ERROR: Missing SYSROOT_LIB: ld-2.24.so” when sysroot is prepared.
cause : New crosstool-ng, keeps the c libs fo 64 bit architectures
(such as armv8a and x86_64) in lib64 folders of cross toolchain
installation directory.
fix : for 64 bit architectures first lokkup the c Libraries in lib64
and then in lib folder of cross toolchain installation directory.

Signed-off-by: Pankaj Bansal <pankajbansal3073@gmail.com>