grub.make: fix grub install issue in a48f8ad
There is a syntax issue in the expressions of installing grub that
makes the recipes have no effect.  So that the sysroot has no grub
commands for installing ONIE or NOS.

    ONIE: Executing installer: tftp://192.168.1.99/onie-updater-x86_64-accton_as7716_32x-r0
    Verifying image checksum ... OK.
    Preparing image archive ... OK.
    ONIE: Version       : 2017.05.31-test
    ONIE: Architecture  : x86_64
    ONIE: Machine       : accton_as7716_32x
    ONIE: Machine Rev   : 0
    ONIE: Config Version: 1
    Installing ONIE on: /dev/sda
    Found a dos partition table in /dev/sda2
    ERROR: grub-install failed on: /dev/sda2
    /tmp/tmp.YbCxvh/installer/install.sh: line 1: grub-install: not found
    ONIE: ERROR: Firmware update URL: tftp://192.168.1.99/onie-updater-x86_64-accton_as7716_32x-r0
    ONIE: ERROR: Firmware update version: 2017.05.31-test
    Failure: Unable to install image: tftp://192.168.1.99/onie-updater-x86_64-accton_as7716_32x-r0
    ONIE:/ #

The patch has been tested in Accton AS7716_32X.

Signed-off-by: Curt Brune <curt@cumulusnetworks.com>