demo OS: wait boot device ready before mouting ONIE-DEMO-OS
In commit fec3ba0, S02init-arch.sh had been renamed to S10init-arch.sh so
that S05mount-demo.sh cannot mount ONIE-DEMO-OS without boot device ready:

    Info: Mounting kernel filesystems... done.
    mount: mounting LABEL=ONIE-DEMO-OS on /demo failed: No such file or directory
    Error: Unable to mount LABEL=ONIE-DEMO-OS on /demo
    Info: Mounting ONIE-BOOT on /mnt/onie-boot ...
    Info: Mounting EFI System on /boot/efi ...

The patch renames S05mount-demo.sh to S11mount-demo.sh for correcting the
mount operation in demo OS.

Signed-off-by: Curt Brune <curt@cumulusnetworks.com>